export * from './account.input';
export * from './student.input';
export * from './class.input';
export * from './historic.input';
export * from './account.filter.input';
export * from './student.filter.input';
export * from './class.filter.input';
export * from './historic.filter.input';
export * from './summary.filter.input';
export * from './summary.input';
export * from './photo.filter.input';
export * from './photo.input';
export * from './communicated.filter.input';
export * from './communicated.input';
export * from './account.login.input'
